### ISSUE TITLE
Get this running with the latest version of Node

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/papyrus#2]
Currently you can only use paperprograms with Node 16. Latest version is 18.

**Comment by jessegreenberg** [comment]
Specifically, the error is 

```
(node:16928) [DEP0128] DeprecationWarning: Invalid 'main' field in 'C:\Users\Jesse\Documents\Development\phetsims\papyrus\node_modules\webpack-dev-middleware\package.json' of 'middleware.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:16928) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Listening on port 3000!
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at filename (C:\Users\Jesse\Documents\Development\phetsims\papyrus\node_modules\babel-loader\lib\fs-cache.js:76:21)
    at C:\Users\Jesse\Documents\Development\phetsims\papyrus\node_modules\babel-loader\lib\fs-cache.js:107:37
    at C:\Users\Jesse\Documents\Development\phetsims\papyrus\node_modules\mkdirp\index.js:51:26
    at FSReqCallback.oncomplete (node:fs:208:5) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0

```

**Comment by jessegreenberg** [comment]
Notes in https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported recommend to 

1) Run with Node option -openssl-legacy-provider
2) Downgrade to Node 16.
3) Upgrade webpack version.

3 seems best, lets try that.

**Comment by jessegreenberg** [comment]
I tried to upgrade webpack and got an error that webpack 5 is not compatible with other dependencies:
```
npm ERR! node_modules/webpack
npm ERR!   webpack@"^5.75.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"2 || 3 || 4" from babel-loader@7.1.5
npm ERR! node_modules/babel-loader
npm ERR!   babel-loader@"^7.1.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps

```

**Comment by jessegreenberg** [comment]
To fix this I followed a series of StackOverflow links from the errors I saw as I made changes.

https://stackoverflow.com/questions/67389400/webpack-unknown-property-query (
https://stackoverflow.com/questions/68356793/error-compiling-ruleset-failed-query-arguments-on-loader-has-been-removed-in
https://stackoverflow.com/questions/49182862/preset-files-are-not-allowed-to-export-objects
https://stackoverflow.com/questions/67333444/no-matching-version-found-for-babel-traverse7-14-0
https://stackoverflow.com/questions/44331005/npm-error-no-matching-version-found-for

I got stuck on the last thread. I need to update babel and related dependencies. When I try to use latest I get 
>npm ERR! notarget No matching version found for babel@^7.20.12.

That version is clearly here: https://www.npmjs.com/package/@babel/core?activeTab=versions. When I try `npm view babel versions` It goes up to 6.23.0. Is my npm registry old or out of date?

**Comment by jessegreenberg** [comment]
This was happening because babel changed its name from `babe` to `@babel/core` between 6 and 7. On to more errors...

https://stackoverflow.com/questions/55055019/cannot-find-module-babel-preset-react

**Comment by jessegreenberg** [comment]
Done, its running on my machine that is using Node 18.

Summary of changes:
- Upgrade babel dependencies (from babel-* to @babel/* in package.json and in .babelrc config files)
- Upgrade webpack and webpack-dev-middleware
- Change some keys in the webpack.config.js to be compatible with latest.
-
